[package]
name = "plz"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.25", features = ["json"] }
tokio = { version = "1.36.0", features = ["full"] }
serde_derive = "1.0.197"
scraper = "0.19.0"
anstyle = "1.0.6"
serde = "1.0.197"
toml = "0.8.10"
clap = "4.5.2"
