[package]
name = "plz"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.0"
reqwest = { version = "0.11.24", features = ["blocking"] }
scraper = "0.18.1"
serde = "1.0.196"
serde_derive = "1.0.196"
toml = "0.8.10"
