name: Rust
on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "README.md", ".github/**", ".gitignore" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Plz
        path: target/debug/plz
